### ISSUE TITLE
Commit ee945e9 causes misalignment on PUBG and Fortnite and potentially other games

### ISSUE THREAD

**Issue by TJ888** [KN4CK3R/UnrealEngineSDKGenerator#26]
Here is a comparison on the game Fortnite, showing the difference between the actual offset of things in game memory, and the aligned offset within the SDK class. -http://puu.sh/xLSCM/a5868d3fbc.png

As shown, many offsets are misaligned by different amounts all throughout the SDK. The built-in function offsetof was used to get these values- http://puu.sh/xLTvA/83fa0ac892.png

Here is a comparison with the exact same dump except with the commit changes undone- http://puu.sh/xLSSr/40e9edc5f4.png

The same deal happens with PUBG from my experience. This is the primary reason why my SDK dumps are far more aligned than everyone else's who does them because they still have this commit in effect, and I was using a really old version of the dumper without this commit. 

PS: Extra edits to the Fortnite project had to be done before this test was started because some things were just outwrite incorrect.

**Comment by KN4CK3R** [comment]
> without this commit
which commit are you talking about?

**Comment by TJ888** [comment]
It says it in the title haha ;)
Commit ee945e9

**Comment by KN4CK3R** [comment]
lol right, haven't seen it :(

**Comment by KN4CK3R** [comment]
With which version/commit of the generator did you generate the sdk?

**Comment by TJ888** [comment]
I just went and downloaded the latest as of right now and it has the exact same issue as my original post. If I undo that 1 commit, while still using the latest version it fixes _all_ misalignment. (_all_ as long as the size of types and w.e else are correct)

**Comment by KN4CK3R** [comment]
Currently I have the problem that the generated sdk isn't valid because the include order of the packages is incorrect.

**Comment by TJ888** [comment]
Oh yeah, I still have a few compilation errors in both PUBG and Fortnite after the dump is completed, but it takes 1~ minutes top to fix, I just go through the errors and fix what it tells me is wrong and done. 
It isn't as many as first appears in the errors output, because multiple of them are just a single problem that once you fix all related errors disappear.

**Comment by KN4CK3R** [comment]
Wasn't talking about the PF_MAX enum value or the "int" member name. ;)
Commit e808cb7 added a new property type of UE4 which introduced errors in the include order. I have fixed them now and will push the changes later.

**Comment by TJ888** [comment]
But there is still the issue of misalignment caused by commit ee945e9. 
What do you have to say about it, are you going to reverse the commit or fix it?

**Comment by KN4CK3R** [comment]
Couldn't start with that without the ability to compile the sdk.

**Comment by TJ888** [comment]
True I guess, but fixing a few compilation errors is easier than manually fixing alignment if you didn't know what commit broke it xD

**Comment by KN4CK3R** [comment]
Have tested now everything and yep, it's wrong. It fails in this case:
```
0x00  <4 byte type>
0x04  missing member
0x08  <4 byte type>
```
The current version "moves" the second 4 byte type to 0x04. My idea was the automatic compiler padding would fill the gap. But that doesn't work for same size types.
